### ISSUE TITLE
Spotify token without browser

### ISSUE THREAD

**Issue by jiridostal** [NicolasHaeffner/plugin.audio.connectcontrol#2]
Hey, I'm really interested in getting this addon to work. However, I'm not able to authenticate on librelec without web browser. If I navigate to URL mentioned in logs, I get "INVALID_CLIENT: Invalid client", which is probably an additional check on Spotify side. Is there any chance to have it fixed or is the project discontinued? Thank you

**Comment by funkyfunked** [comment]
I get the same thing on Ubuntu 16.04, but with Chromium installed. Im using the official spotify client on the same machine, running always in the background. If i try to start the plugin, my browser opens and i get the exact same error:

INVALID_CLIENT: Invalid redirect URl

My client ID and secret are right for sure, help appreciated.

**Comment by jiridostal** [comment]
I'm afraid this is not the same error, as I got "Invalid client" and you have "Invalid redirect URI". Your error is commonly caused by missing "/" at the end of redirect url you set on Spotify side.
